workspace:
  base: /drone
  path: src/github.com/drone/drone

pipeline:
  build:
    image: alpine
    commands:
      - echo "Building..."
      - touch drone-upload
    when:
      event: push
  publish:
    image: s3
    environment:
      - AWS_ACCESS_KEY=$$AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY=$$AWS_SECRET_ACCESS_KEY
    acl: public-read
    region: "us-west-1"
    bucket: test-drone-uploads
    source: drone-upload
    target: /drone-upload
    when:
      event: push
      branch: master